### ISSUE TITLE
Will this work with Linux (Raspberry Pi/Debian)?

### ISSUE THREAD

**Issue by Lakster** [polaris-/dwc_network_server_emulator#1]
I was wondering if this server software would work with Linux, specifically the Raspberry Pi which runs a modified version of Debian (called Raspbian)? I've never used Python code before, so if you could offer a brief explanation of how to set it up/run it or provide a link to to a good source of information, that would be appreciated as well. Thanks!

**Comment by bi0shacker001** [comment]
Python is an interpreted language, so it is inherently cross-platform.
Provided the server isn't using any precompiled binaries, it should run on
a Pi.

On Wed, Apr 9, 2014 at 6:35 PM, Lakster notifications@github.com wrote:

> I was wondering if this server software would work with Linux,
> specifically the Raspberry Pi which runs a modified version of Debian
> (called Raspbian)? I've never used Python code before, so if you could
> offer a brief explanation of how to set it up/run it or provide a link to
> to a good source of information, that would be appreciated as well. Thanks!
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/polaris-/nintendo_dwc_emulator/issues/1
> .

## 

-Jonathan Schuett
NeuralNet Technologies
5709951817
Bioshacker001@gmail.com

**Comment by polaris-** [comment]
Thanks for showing interest in the project!

I'm unsure how well it would run on a Raspberry Pi, but as far as I know, none of the code I've written and none of the libraries tie it to any specific operating system so as long as you are able to install the required software listed in the readme then it should work on Linux.

As for a guide on how to set it up: At the moment the server is very user unfriendly and is nowhere near being ready yet, so I'm going to leave the setup as a little bit of a barrier to entry for now. I put instructions on the wiki in the future once it's more stable.
