### ISSUE TITLE
I could host a server... wfc.kentwillfred.com

### ISSUE THREAD

**Issue by DillPo313** [polaris-/dwc_network_server_emulator#11]
I can create a sub-domain and host a server on that.

**Comment by polaris-** [comment]
Thanks for the offer, but there is no need for any more servers at the moment. You can find the IP of the server we are using on the Wiki page if you are interested in trying it out. Please note that it does goes down occasionally since the server is still under development.

**Comment by DillPo313** [comment]
Ok, if you ever change your mind. Email me at admin@kentwillfred.com
