### ISSUE TITLE
Mario Kart DS unable to connect.

### ISSUE THREAD

**Issue by ghost** [polaris-/dwc_network_server_emulator#13]
When I connect to MKDS with everything it said to do on the wiki, it says "unable to connect, error code 20100. 
I have erased my save, set the auto obtain DNS to "no", set primary and secondary DNS to 75.127.5.215.
I am using a USA/English version of the game.
Please help

**Comment by ToadKing** [comment]
Have you applied the NoSSL patch to your game?

**Comment by Noremon** [comment]
I'm having this issue too, but with Last Spectre & a physical 3DS. It can connect to my wireless network, I've deleted the ID, but I keep getting 20100. I can't even connect in Test Connection in the settings without using a game. The System Info ID area is blank too.

**Comment by Abelplov7l** [comment]
Will it be possible to make original games to connect ? 
I also get the same error as kairu

**Comment by ghost** [comment]
Since I have realized I needed the NoSSL code, this issue is irrelevant~
Closing this for now
