### ISSUE TITLE
DNS input

### ISSUE THREAD

**Issue by Garnium** [polaris-/dwc_network_server_emulator#14]
For the 3rd set of characters for the DNS, it will only allow me to input 2 characters instead of just the one. Therefore, I cannot input the 5 alone to connect to the server. How could I fix this?

**Comment by Noremon** [comment]
Hit the right arrow and it will go to the next set.

**Comment by Garnium** [comment]
Actually, I'm on my DSi and hitting the right button only moves the cursor to select the numbers to input.

**Comment by Noremon** [comment]
Not the button, the "→" in the input on screen.

**Comment by Garnium** [comment]
Crap, I didn't think of that. I didn't even notice it. Thanks.
