### ISSUE TITLE
Mario Kart DS 

### ISSUE THREAD

**Issue by Abelplov7l** [polaris-/dwc_network_server_emulator#17]
Hi,
When I apply the nonSSL patch to my mario kart DS ROM(USA) the game is not oppened by my R4, 
I tried on  Europe Version and in USA version, both aren't working for me after I apply the nonSSL patch
What can I do?
It only worked on the Japanese mario kart DS version , but , unfortunately the japanese version can't connect to the server yet :(
Thanks, Abel

**Comment by vaguerant** [comment]
I recommend you re-read the [instructions](https://github.com/polaris-/dwc_network_server_emulator/wiki). Mario Kart DS is known not to work with SSLPatcher, use the provided xdelta patch instead. Not a bug with the DWC emulator.

**Comment by Abelplov7l** [comment]
thanks
Yes I did  It it works now! 
Is there an AR code for connecting to the server at this moment?

**Comment by AdmiralCurtiss** [comment]
Not yet but there will be soon, they'll be listed on the Wiki.
