### ISSUE TITLE
Pokémon - Battle Tower (G4) and Subway (G5) don't work.

### ISSUE THREAD

**Issue by lordtu** [polaris-/dwc_network_server_emulator#18]
global terminal does not work any option, only connect, the same goes in the underground battle in the Wi-Fi station.

**Comment by AdmiralCurtiss** [comment]
The server appears to be down at the moment, but once it's up the GTS should work.

You are, however, correct that the Wi-Fi Battle Subway (and the Wi-Fi Battle Tower in Generation 4) aren't working yet, someone needs to implement that part of the Pokémon servers.

**Comment by lordtu** [comment]
thanks for answering and congratulations for the work you are doing, keep so ;), other than what I mentioned above do not work the random matchup, send and recibe musical photos and battle videos.
