### ISSUE TITLE
Exception "variable 'now' referenced before assignment"

### ISSUE THREAD

**Issue by Leseratte10** [polaris-/dwc_network_server_emulator#2]
Sometimes there is an Exception "variable now referenced before assignment". 

You can simply fix this error by moving line 301 in file gs_database.py ("now = int(time.time())") above the first SQL query. Here is a patch for this error: http://wfc-share.com/gs_patch.diff

**Comment by polaris-** [comment]
Thanks for the bug report. It should be fixed as of the latest revision.
