### ISSUE TITLE
Regression in matchmaking for Mario Kart DS, possibly others.

### ISSUE THREAD

**Issue by vaguerant** [polaris-/dwc_network_server_emulator#20]
For the last 12+ hours matchmaking in Mario Kart appears to have become broken using altwfc. The stats server has been listing over 20 users (and later over 30) for all of that time, but even when users are confirmed searching on IRC, no other players can be found. Confirmed by a number of users; myself, BarronWaffles, Italy, Sev7n1, Azor. I've personally played with Waffles previously and am able to play other titles such as Zelda: Phantom Hourglass with him.

The game Sonic & Sega All-Stars Racing shows essentially identical behavior. Connections to the server go through, but the search phase never finds any other players (in either "anyone" or "friends" mode). Confirmed this behavior with BarronWaffles, we were unable to find each other on either mode. I will note, however, that I had not previously verified Sonic Kart as working, so the problem may be unrelated.

**Comment by Abelplov7l** [comment]
same for me in mario kart DS, when I search on friends I can see the blue man of my other friends but unfortunately we couldn't find each other :(

**Comment by Abelplov7l** [comment]
Oh, and I think it's not only with atlwfc method
I used a flash card with a nonssl mario kart ds ROM and It also doesnt work x(

**Comment by ghost** [comment]
Connection fully works however matchmaking seems to be quite a problem. I have encountered several people online, but it rarely works for me.

**Comment by TiBiUan** [comment]
Hello,

I also have matchmaking issues with MKDS. I can connect, but regardless of the search mode, I never seem to find other racers. It rarely happened that I would have one hit, but it would disappear prior to the match start.
Also, despite reciprocally adding our friend codes, some of my friends could not see the friend search icon when I was friend searching. It also happened that I saw the icon without any online friend in my list...
