### ISSUE TITLE
DeSmuME not connecting to server

### ISSUE THREAD

**Issue by antonio22** [polaris-/dwc_network_server_emulator#23]
hi guys, I used one of the old wifi builds of desmume, changed dns, but was not able to connect to the WFC.

anyone can advise other settings or what to fix in the source code to compile the emulator working with wifi emu

**Comment by antonio22** [comment]
EXPERIMENTAL_WIFI_COMM preprocessor still work?

**Comment by polaris-** [comment]
This is not an issue with the server so I'm closing it. We're not going to offer support for an emulator that is known to have buggy wifi code. Please find an emulation forum and ask there.
