### ISSUE TITLE
R4i Flash Card Option?

### ISSUE THREAD

**Issue by ncrouch141** [polaris-/dwc_network_server_emulator#28]
Is it possible to use a flash card like this one to connect to the server? How would I do it? 

![r4i_gold_3ds](https://cloud.githubusercontent.com/assets/7716162/3095432/b9a74954-e5c7-11e3-9d4f-cb47ec62ac77.jpg)

**Comment by ToadKing** [comment]
Yes you can.

Please do not use GitHub for questions our troubleshooting. Use IRC or [this thread](http://gbatemp.net/threads/save-nintendo-wifi-a-project-to-save-online-servers-for-ds-and-wii-games.362717/) instead.
