### ISSUE TITLE
Mario Kart DS Matchmaking Issues

### ISSUE THREAD

**Issue by Shaom2** [polaris-/dwc_network_server_emulator#31]
When i search a player in Worldwide match i don't find any peoples i read an issues topic like my. can an admin answer me??' please i need help

**Comment by AdmiralCurtiss** [comment]
Probably just means that no one else is online and searching for matches.

**Comment by Shaom2** [comment]
hmm,this is impossible i have tried to connect two ds a ds lite and a 3ds on the same network but nothing, THE MATCHMAKING IS BROKEN!!  i have found an other post with the same problem in MKDS and Sonic And Sega All Stars Racing

**Comment by Abelplov7l** [comment]
Yeah this problem should be solved. Matchmaking really doesn't work in mario kar. DS :(

**Comment by bi0shacker001** [comment]
It's likely that some errors were unknown because the official DS servers
were still online.

On Sun, Jun 1, 2014 at 2:04 AM, Abelplov7l notifications@github.com wrote:

> Yeah this problem should be solved. Matchmaking really doesn't work in
> mario kar. DS :(
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/polaris-/dwc_network_server_emulator/issues/31#issuecomment-44768545
> .

## 

-Jonathan Schuett
NeuralNet Technologies
5709951817
Bioshacker001@gmail.com
