### ISSUE TITLE
Brawl error code 85010

### ISSUE THREAD

**Issue by ChimeraUltima** [polaris-/dwc_network_server_emulator#32]
Every time I select With Friends or Basic Brawl, I get disconnected within less than a minute, with the message "Disconnected from network during transmission. Error Code: 85010" I followed the instructions, changed primary and secondary dns, deleted my save file, ran offline network enabler, and load the game through brainslug. I've had no problem playing online until just recently. Is this a problem with the server, or maybe my internet connection?

**Comment by polaris-** [comment]
Is this still an issue? We were having some server stability issues but they should be fixed now.
