### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by Storm-6V** [polaris-/dwc_network_server_emulator#33]
I am using the AR to play on mph. For the first few days, my connecting was fine. But then I got an error code 52100 "You connected to an access point but were unable to connect nintendo wfc." I restarted it again, and it said the same thing. It's been happening for a day now. Help!?

**Comment by polaris-** [comment]
The server has been down since yesterday. We hope to have it up and running again sometime tonight or tomorrow. So try again in a few days and see if anything changes then.
