### ISSUE TITLE
Error code 20100

### ISSUE THREAD

**Issue by teruy** [polaris-/dwc_network_server_emulator#35]
I dont have AR for my 3ds, so i used Rom patcher. I followed instructions without any single mistake and set up new connection point. I tried it out and connection was successful. All configuration was made in start game menu. Then i tried to connect ingame (Yu-gi-oh world championship 2011 over the nexus) and got this 20100 error code. I even tried to patch another rom after but got the same result.

**Comment by vaguerant** [comment]
How many connections do you have set up on the DS? It has no way to set a preferred connection, so it sounds like you're still connecting to the Nintendo server on a previous connection setup--20100 is the "service has been shut down" error. You're probably just getting that from Nintendo rather than this being an issue with this server.

**Comment by condret** [comment]
20110 is "service has been shut down". 20100 happens if you don't patch the rom. (I think that there must be a way to make patching unnecessary. )

**Comment by einstein95** [comment]
The only way to make patching unnecessary is if we got Nintendo's SSL certificate.

**Comment by condret** [comment]
hm, I'm not very familiar with ssl, but can't we get that from some traffic-dumps (if we have some).

**Comment by condret** [comment]
or maybe we should just ask nintendo

**Comment by einstein95** [comment]
1) SSL certificates like this aren't transferred via the connection, only a hash of the certificate
2) HAH, like Nintendo would ever do that

**Comment by polaris-** [comment]
If this is still an issue then please comment and and I'll reopen the ticket. For now I'm closing it since it hasn't been touched in 5 months and want to clean up the error reports.
