### ISSUE TITLE
Allow the WII to succeed the connection test. 

### ISSUE THREAD

**Issue by SMTDDR** [polaris-/dwc_network_server_emulator#38]
```
https://www.cloudshark.org/captures/e4f3db63efde
```

The above capture is the WII succeeding in a connection test.

There's no SSL here so I'm hopeful it's possible to handle this in the polaris system. For some reason the whole OfflineNetworkEnabler and/or Brainslug won't let the USBLAN to work. While it would be ideal for that problem to be fixed, it would also be nice to just bypass needing O.N.E. and Brainslug entirely. Then a Riivolution patch to remove the naswii SSL connection from games. Then people can go online just using riivolution and have their usblan hardware functional. This is how I go online; I can temporarily tamper with traffic after entering the polaris DNS to allow the connection-test to pass... then I stop tampering to allow it to go to polaris DNS and I'm online with my usblan.

EDIT: I'll be adding more details to this in a day or 2... like the pcap capture of polaris handling the connection test and suggestions on what to change.

**Comment by SMTDDR** [comment]
Oh.... polaris DNS returns the official server's IPaddress for wiinat.available.gs.nintendowifi.net . I guess that solution works as long as Nintendo keeps that stuff running.

**Comment by SMTDDR** [comment]
Turns out I forgot to remove my iptables rules manipulating DNS traffic that allowed connection test to pass regardless of the WII's DNS settings.

```
https://www.cloudshark.org/captures/ce7ab478b4b4
```

Notice that php source code was returned in the HTTP connection response. It appears that php code was meant to set the response headers. That should probably be fixed first. If that doesn't solve the connection issue then perhaps the WII does a checksum on the response and it must truly match exactly what is returned from the official servers.

**Comment by mdbell** [comment]
I fixed the php issue with conntest, hopefully it will succeed now.

**Comment by SMTDDR** [comment]
Fantastic, it passes the connection test now.

Thanks, :+1:
