### ISSUE TITLE
Will Pokémon games work with the server?

### ISSUE THREAD

**Issue by RicoSantos** [polaris-/dwc_network_server_emulator#42]
I have tested Pokémon Black 2, it connects fine but none of the online options worked.
I know the server isn't a magic thing, but I just wanted to know if the online options of the game may work someday.

**Comment by AdmiralCurtiss** [comment]
What online options are you having problems with, exactly? Pokémon has lots of custom online stuff that needs to be reimplemented one-by-one.

**Comment by RicoSantos** [comment]
Everything, unfortunately. I mean, I can connect with the custom server, but the game online functions doesn't work (like you said online stuff needs to be reimplemented one-by-one). The only one I couldn't test was the WiFi Club, because I can't test it alone.

**Comment by ghost** [comment]
can i add Pokémon Games in compatibility list as Not working?or to be reimplemented?

**Comment by RicoSantos** [comment]
There are still things that need to be tested like the GTS Negotiations and the Wifi Club.

**Comment by mm201** [comment]
I put up a replacement anti-cheat server (pkvldtprod.nintendo.co.jp) that simply approves everything (for now). This ought to make more stuff work on Black & White but needs to be tested. (GTS is working again.)

**Comment by RicoSantos** [comment]
Awesome news! 
Now I need help to test the Random Machup and GTS Negotiations.

**Comment by ghost** [comment]
oh,if this approves everything verify be succesful,i will get over,and probally,i will make tests in GTS Negotiations and Random Matchup,and Communication System in Gen 4

**Comment by RicoSantos** [comment]
I think Pokémon games need a really powerful server. Or maybe the server just can't have multi connections for those games yet. 
I've recorded a GTS trade between emulators: www.youtube.com/watch?v=nTxSyZBDEUM

**Comment by mm201** [comment]
@ZilverXZX: Are you sure there's another player online when you visit Random Matchup? GTS is working for others here.

GenIV's Union Room is for local wireless only. You're looking for the Wi-fi Club (which has been tested and works).

**Comment by MarcoMeter** [comment]
Is it currently possible to trade Pokemon on Heartgold or Soulsilver? After al,l great job within this short time.

**Comment by ghost** [comment]
Mystery Gift Gen 4 Works,if Gen 5 Mystery Gift need to be implemented.

PS:B2W2 Download Tournaments works

**Comment by aasquasar** [comment]
Is there any chat to do trades and battles?

**Comment by AdmiralCurtiss** [comment]
We have figured out the Gen 5 Mystery Gift download conditions, might as well document it somewhere.

attr2 in the file list is a bitmask representing the versions the gift will download to.
0x100000 is White
0x200000 is Black
0x400000 is White 2
0x800000 is Black 2

After downloading the gift, the game can still reject it; it looks like there's another version check in the mystery gift file itself, as well as a checksum. Should be simple to figure out, expect a full set of Mystery Gifts soon!

**Comment by ghost** [comment]
and the battle tower from platinum

**Comment by mm201** [comment]
I finished Battle Tower a couple weeks ago. (Unfortunately, the main server has been down for about that long.)

I would suggest closing this issue, since altwfc already has full Pokémon support at their end and all remaining issues are unimplemented things on mine.

https://github.com/mm201/pkmnFoundations/issues

**Comment by polaris-** [comment]
I'm going to close this ticket now for reasons mm201 mentioned in his last response. Please report any Pokemon-related feature requests or bugs (besides Mystery Gifts, which are handled on our server) to the issue tracker here: https://github.com/mm201/pkmnFoundations/issues
