### ISSUE TITLE
Remove need for changing DNS settings.

### ISSUE THREAD

**Issue by SMTDDR** [polaris-/dwc_network_server_emulator#45]
It would be nice if you created a domain name the same string length as "nintendowifi.net" that will point to your server and be accepted by your apache config when it sees that host in the Request's Host header; doing the same thing it would have if the host said "nintendowifi.net". I could make a Riivolution patch that replaced all "nintendowifi.net" with "ramen.altwfc.net" and thus people won't need to change their DNS settings. They'll just start riivolution and I'd provide a patch called "Use altwfc servers".

Background

```
http://forum.wii-homebrew.com/board42-kreativitaet/board329-mkw-server-project-english/51700-multi-game-support/index18.html#post6001481
```
##### TL,DR - Make the subdomains "*.ramen.altwfc.net"(same string length as "nintendowifi.net") point to altwfc's IPaddress and Hostname "*.ramen.altwfc.net" be accepted on your apache config the same way "nintendowifi.net" currently is.

Right now, this is what I see:

```
pikachu@BATTLEGYM ~ $ nc -v 75.127.5.215 80
Connection to 75.127.5.215 80 port [tcp/http] succeeded!
POST /ac HTTP/1.1
User-Agent: RVL SDK/1.0
Host: ramen.altwfc.net
HTTP_X_GAMECD: STKE
Content-Type: application/x-www-form-urlencoded
Content-Length: 309

action=bG9naW4%2A&gsbrcd=U1RLSjBsbzRjOXI%2A&userid=MTYwODEzMjkwNjg4Mw%2A%2A&ingamesn=AFMATQBUAEAARABEAFIAIAAg&sdkver=MDAxMDAw&gamecd=U1RLRQ%2A%2A&makercd=MDg%2A&unitcd=MQ%2A%2A&macadr=MDAxN2FiNDQ3N2M5&lang=MDE%2A&devtime=MTExMDE1MDgyOTQ4&csnum=TFUxMDM0MjE4ODc%2A&cfc=NjIzNjM1OTUzNTYxNTg5MQ%2A%2A&region=MDE%2A


HTTP/1.1 404 Not Found
Date: Sun, 29 Jun 2014 16:55:13 GMT
Server: Apache/2.2.22 (Debian)
Vary: Accept-Encoding
Content-Length: 282
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /ac was not found on this server.</p>
<hr>
<address>Apache/2.2.22 (Debian) Server at ramen.altwfc.net Port 80</address>
</body></html>
```

**Comment by mm201** [comment]
Anything that makes accessing the server easier is good in my books. Especially since this is just an Apache configuration, it should be trivial to add.

Keep in mind that some games have their own servers located on non- nintendowifi.net domains, and would require their own special patches for this to work.

**Comment by SMTDDR** [comment]
@mm201 

Really? ugh, I want one riivolution patch that resolves this completely. Could you give me an example of URLs of any game that talks to servers not ending in "gs.nintendowifi.net"?

**Comment by mm201** [comment]
Pokémon Platinum and onward communicate with pkgdsprod.nintendo.co.jp for Global Terminal things (battle videos and some gimmicks). Pokémon Black/White and onward communicate with pkvldtprod.nintendo.co.jp for anti-cheat. They also communicate with one of several subdomains at pokemon-gl.com for Game Sync. (The subdomain depends on the language of the game.)

**Comment by ghost** [comment]
yes,because every server have a different communication,like in black & white,use the pkvldtprod for anti cheat,but nobody likes that

**Comment by mm201** [comment]
It doesn't matter if you like it. The game hangs and returns an error message if there's no response from the server.

**Comment by SMTDDR** [comment]
@mm201 
Ah, so just 2 domains? nintendowifi.net and nintendo.co.jp that you know of?

**Comment by mm201** [comment]
There's a third one in there, pokemon-gl.com.
Also, it's only Pokémon I've been researching. Other games could be using anything.

**Comment by SMTDDR** [comment]
@mm201 

(╯°□°)╯︵ ┻┻

I wanted a generic riivolution patch. The info you have given me makes it clear that each game may end up needing its own specific changes.  Closing this github issue, a *.ramen.altwfc.net domain resolve isn't going to accomplish what I hoped.

**Comment by mm201** [comment]
There's no reason you can't make a patch that works for the generic games without special servers. I don't even know which (if any) Wii games use special servers. A general purpose patch could still work 99% of the time.

**Comment by SMTDDR** [comment]
@mm201 ....oh...these servers you've mentioned are only for Nintendo's handheld systems that you know of? I'm hoping all WII games stick with "gs.nintendowifi.net".

**Comment by mm201** [comment]
See the [compatability list](https://github.com/polaris-/dwc_network_server_emulator/wiki/Compatibility) for a list of games which are working with only basic *.nintendowifi.net connectivity.

Requiring DNS or a custom patch for a small subset of games isn't that big a problem.

**Comment by SMTDDR** [comment]
@mm201 
Interesting. I guess that makes sense, all those games are working when pointed to altwfc's DNS which only redirects nintendowifi.net requests afaik. I sure would like to see the network captures of the games that don't work on that list.

**Comment by mm201** [comment]
The thing is, there are several different reasons a game might fail. Requiring a custom server is only one of them. They might require a custom gamestats server (custom, but hosted under nintendowifi.net), or use unimplemented parts of the Gamespy protocol.

Edit: And altwfc is redirecting pkvldtprod.nintendo.co.jp requests to my server.

**Comment by SMTDDR** [comment]
@mm201 
True... but still curious to see if any of them is a simple'ish fix.

Edit: And yeah, I forgot that altwfc deals with more than just WII games.

**Comment by SMTDDR** [comment]
Excellent,

```
pi@raspberrypi ~ $ ping ramen.altwfc.net
PING ramen.altwfc.net (75.127.5.215) 56(84) bytes of data.
64 bytes from host.colocrossing.com (75.127.5.215): icmp_req=1 ttl=53 time=218 ms
64 bytes from host.colocrossing.com (75.127.5.215): icmp_req=2 ttl=53 time=126 ms
64 bytes from host.colocrossing.com (75.127.5.215): icmp_req=3 ttl=53 time=132 ms
^C
--- ramen.altwfc.net ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2014ms
rtt min/avg/max/mdev = 126.031/158.931/218.175/41.978 ms
```

Looks like *.altwfc.net points to your custom server, this is good enough for now to experiment making a riivolution patch that'll replace "nintendowifi.net" with "ramen.altwfc.net". The only catch now is the fact that the game will set the request header as <code>Host: ramen.altwfc.net</code>, which will result in a 404 response from your system because you're expecting <code>naswii.nintendowifi.net</code> but I'll have a proxy setup such that the riivolution patch will replace <code>https://naswii.nintendowifi.net</code> with <code>http://altwfc.ramen.dontrush.me</code> so I can get all the requests, change the header and send them to altwfc's server.

All the non-naswii requests, I can patch <code>_.gs.nintendowifi.net</code> into <code>_.japan.gs.altwfc.net</code> ...same length string.

**Comment by SMTDDR** [comment]
Okay, riivolution patch works... I can get online without changing my DNS settings.

```
https://www.cloudshark.org/captures/d638a18f5333
```

The only catch is altwfc's apache rejection of <code>naswii.ramen.altwfc.net</code> as a valid host request headers. If that was fixed, then there would be no need of my custom server to rewrite that request.

**Comment by SMTDDR** [comment]
I guess this won't be happening

**Comment by kyle95wm** [comment]
It's sad really, I was really hoping we could have something like this

**Comment by mm201** [comment]
It's easy to add, you just need to kick the right person. Probably Nagato or Eearslya.
