### ISSUE TITLE
Pokemon Mystery Gifts

### ISSUE THREAD

**Issue by Galatean** [polaris-/dwc_network_server_emulator#46]
Will there eventually be a way to control which mystery gift is received? Perhaps by checking the date the connecting system is set to?

Also, will Black/White/Black2/White2 eventually have their mystery gifts added?

**Comment by AdmiralCurtiss** [comment]
You know, letting the user control the mystery gift to receive by setting the DS' date is a great idea, I think I'll implement just that.

As for BW, unfortunately I have yet to figure out how to get the game to download a mystery gift from the server, it just requests a list of files and then aborts. Once that's figured out I'll add them.

**Comment by Galatean** [comment]
Cool. Glad my suggestion had some merit. I wasn't sure if the server could read the device's date/time. Should I leave the issue open as a reminder?

**Comment by polaris-** [comment]
During the login process, the device sends the "devtime" field so it should be possible to look up the local date and time of the device at login. I'd leave the issue open and let AdmiralCurtiss decide when to close it.

**Comment by AdmiralCurtiss** [comment]
Implemented in 2f29689.

**Comment by Galatean** [comment]
Has this been built to the public test server yet? I was trying it, and my understanding is that if I wanted to select the 8th item on a list of 29, I would set the system date to 8 Jan. However, I got a random item, as I usually did.

I just wanted to verify whether I was supposed to be able to do this on the public test server yet before raising an issue about it.

**Comment by polaris-** [comment]
The update is running on the server as of now. Try again.

**Comment by Galatean** [comment]
Definitely works. However, I noticed that the code counts the list from 0(it's an array, after all), which means to get, for example, item no. 9 on the list you need to set the calendar date to something that gives a mod result of 8, and to get the first item on a list, you need to set the date to something that gives a mod result of 0. I'll see if I can add a bit of instruction on the wiki for how to use the function. Any suggestion on which section to put it under?

**Comment by AdmiralCurtiss** [comment]
I suppose it would be more logical to the user to get item number 1 on Jan. 1st, yes. I'm gonna change that slightly, so account for that when you write wiki instructions.

As for where to put them, either make a new page or put it on https://github.com/polaris-/dwc_network_server_emulator/wiki/Nintendo-DS-Download-Content

**Comment by Galatean** [comment]
Wiki instructions added under Nintendo DS Download Content page. Please feel free to criticize. I've tried to keep it as simple as possible for the non-technically minded users.

**Comment by ghost** [comment]
i dint get it the number,i confused,is for place in a order or something,because i dont get it(i will test in a gen 4 game,pokemon pearl)

EDIT:like,936 17p of CPUE Gifts,what this is for,because i dont known the date to set here

**Comment by Galatean** [comment]
Please elaborate. What is the process you followed?

**Comment by ghost** [comment]
well,i make exactly like siad,but i dont get the number in the side of the item,but i dont get the number,like the 936,what i need to do with the number

**Comment by Galatean** [comment]
I see the problem. You picked the wrong side. If you don't see an ascending series of numbers on the left side (like 1,2,3,4,5, and so on) then you'll need to count the lines by hand. Start at the top, that's line number 1, the next is line number 2, and so on. Those are the line numbers the wiki instructions are talking about. 936 is something you can ignore completely.

**Comment by ghost** [comment]
Line 22,okay,22 is for date?like 2/2?

**Comment by Galatean** [comment]
No, line 22 means the 22nd day of the year, so 22 January.

**Comment by ghost** [comment]
well,i made two test,and the 2 have succesful,the first is with the matchup checker app(yeah,i received the app)and the second give to me a entei of the event Legendary Beasts of Johto.

**Comment by dmoeenm** [comment]
Hello i know this issue is closed but i have to ask can anyone get mystery gifts in pokemon diamond or pearl because both my pokemon diamond's just dissconect me when i try to recive a mystery gift giving me error 31020
