### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by polaris-** [polaris-/dwc_network_server_emulator#47]
So it's finally time to bring up the issue of licensing. The biggest thing we want out of the license is for the server to stay open source and for people to be required to contribute back any changes they make. Naturally I'm leaning toward something in the GPL family because of the last requirement.

@ToadKing suggested on IRC the use of the AGPL license for this project which seems like a decent fit for this project. 

That leaves @AdmiralCurtiss and @msoucy.

Opinions?

**Comment by AdmiralCurtiss** [comment]
AGPL v3 sounds fine to me.

**Comment by polaris-** [comment]
Alright, so 3 for AGPL v3. I guess that leaves @msoucy then.

**Comment by msoucy** [comment]
I'm fine with it, assuming that any legacy code that was brought in was AGPL compatible.

**Comment by polaris-** [comment]
All of the server code itself should be compatible with AGPL. Most of it was written by me or one of the other developers and a very small amount of it was ported from outside sources (Luigi's code for example). The dependencies seem like they should be fine as well (one MIT and the other GPL compatible).

Luigi's code should also be fine because the clause says "This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version." Interpreting that last part of the statement to mean that we can consider it to be GPL v3 instead of v2, then AGPL v3 and GPL v3 are compatible from what I've been able to gather, so we should be in the clear.

I guess we'll be licensed under AGPL v3 unless someone has something else to say. I'll start making the changes soon.

**Comment by polaris-** [comment]
Alright, the license is in place now. I've credited everyone on a per file basis using Github's contributors list. I've also credited based on Github name. Please feel free to update the license text to include your real name and/or email address if you wish.
