### ISSUE TITLE
[Question]: Is it possible to run this server on a LAN?

### ISSUE THREAD

**Issue by Galatean** [polaris-/dwc_network_server_emulator#48]
I want to create a local copy of the server to play around with, but I'm not sure how or whether it's even possible at this stage.

I'd also like to ask what the file formats for the dlc actually are.

**Comment by AdmiralCurtiss** [comment]
Yeah, you can easily do that, it's what I'm doing for testing. You just need to setup your own DNS server to get the games to connect to your local server copy.

And I'm not exactly sure what you mean with the DLC question.

**Comment by ToadKing** [comment]
The DLC format depends on the game.

**Comment by Galatean** [comment]
Well, let's take the Mystery Gifts for example.

Is the format just a renamed .pgf file? Or is it a custom format?

Same question for the other formats.

**Comment by polaris-** [comment]
All games use their own custom formats.

**Comment by Galatean** [comment]
I see. Is it a Nintendo format? If so, where did you get the files from? I want to see if I can figure out what's up with the Gen V mystery gifts failing.

**Comment by AdmiralCurtiss** [comment]
There's no common format, a game just requests a file from the download server and gets it, and then does whatever it wants with the downloaded content.

In Pokémon Gen 4 specifically, it's a modified version of the data that's stored in the save file when downloading a mystery gift, where the description part of the file is copied to the start of the file. See https://github.com/AdmiralCurtiss/MysteryGiftConvert

**Comment by AdmiralCurtiss** [comment]
Oh, and the problem with the Gen 5 mystery gifts is that the game doesn't even attempt to download a file after requesting the list of available files. It's quite odd, presumably it checks for something specific in the file list that we haven't figured out yet.

**Comment by Galatean** [comment]
I see. Thanks! That answers all my questions.

**Comment by Galatean** [comment]
I decompiled one of the Gen V roms, and found utility.bin in the dwc directory. I think one might be able to find the list parsing code in there, but I can't find the right utility to open the file formats that I think contain what I'm looking for once I've decompressed them.

**Comment by ghost** [comment]
well,if you open,the Gen 5 Mystery Gift will work,i just need to solve a problem with my wifi desmume and error code
