### ISSUE TITLE
Error Code 52000

### ISSUE THREAD

**Issue by ghost** [polaris-/dwc_network_server_emulator#49]
I Try to connect,but dont connect,just show to me error code 52000,what i make wrong,because my pokemon diamond work,but i doesnt connect in mystery gift,and gts too,what i need to do now?

**Comment by ghost** [comment]
i already solve,i try to use realtek instead of Attansic,then,problem solved

**Comment by ghost** [comment]
the error it's back,but the strange is that my configuration is correct,attansic,but not connect to the altwfc

Game Used:Pokémon HeartGold
Desmume Version(s):0.9.9 wifi 4334 x64 and 0.9.7 3947 wifi x64

**Comment by ghost** [comment]
solved again,i think,because i need to test the GTS

**Comment by User51** [comment]
Hey excuse me i have the same problem i keep getting error 52000 can u guide me plz

**Comment by User51** [comment]
But on a real console

**Comment by User51** [comment]
can you help me
