### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by JzargoTheMage** [polaris-/dwc_network_server_emulator#50]
I tried to connect using both a retail copy and an emulated version of Pokemon Pearl today. The first problem was with the retail copy. Either the AR code the WfcReplay program generated isn't working right or my Internet configuration just doesn't like my DS Lite. (It was unable to obtain IP address, not sure what could cause it.) The second problem was with the emulated version. When I _finally_ got DeSmuME set up correctly to use the internet, I tried connecting and got error number 23404 (service has either high traffic or is temporarily down). I may have just connected at a bad time while updates were being made, but I'm not sure as there's no way to check the server status that I know of. Thanks in advance!

EDIT:  Yes, I was using a patched version of Pearl for emulation. I will also be attempting to fix the IP issue with a manual setup for the retail copy. More news later. Also, I need to figure out how to catch packets :P

EDIT 2: Have the software installed, but not sure how to disable offloading. Emulated version of Pearl still won't connect with error 23404. About to try with packet capture (may be issues if offloading interferes, but whatever).

**Comment by JzargoTheMage** [comment]
So from a bit of research I've done, I'm even more confused. There's 2 types of offloading listed here: 

http://www.speedguide.net/articles/windows-7-vista-2008-tweaks-2574

One is supposedly disabled by default in Vista (TCP Chimney, I believe) but the other would still need to be disabled manually. Which one is important to have disabled for packet capture? (_Not a tech guru_)

**Comment by JzargoTheMage** [comment]
REALLY LATE Update: I did email my capture to Toad, but as there has been no update here I'm assuming he is inactive on this project. I can find it and resend it to someone else if necessary.

**Comment by ToadKing** [comment]
I'm only hosting dumps from the official servers on my site.

Pokemon is known to not have everything supported, and dumps of non-working features won't help until somebody starts working on them.

**Comment by JzargoTheMage** [comment]
Alright then. I WOULD start on them myself, except for the fact that I have little to no programming knowledge, only extremely basic Python. :P I could try to find someone that's interested in this if it helps. Until then I'll close this. Thanks for the response!
