### ISSUE TITLE
More Pokemon Events Here

### ISSUE THREAD

**Issue by RenegadeRaven** [polaris-/dwc_network_server_emulator#507]
I've compiled the entire English Gen 4 Events from projectpokemon if you don't already have them all.

[dlc.zip](https://github.com/barronwaffles/dwc_network_server_emulator/files/2711230/dlc.zip)

**Comment by barronwaffles** [comment]
Oh, neat. Thanks!

Would you like to generate updated list files and do a pull request?
If not I'll be able to take care of integrating it sometime later in the week.

**Comment by RenegadeRaven** [comment]
Is there a reason why the list files have a column of 936?

**Comment by barronwaffles** [comment]
That's a file size attribute, also - note that the tabs between columns are critical.

Not terribly readable with their current formatting, might be something to update in the future.

**Comment by RenegadeRaven** [comment]
are they needed? i was thinking of doing something like this:
[_list.txt](https://github.com/barronwaffles/dwc_network_server_emulator/files/2711527/_list.txt)

**Comment by barronwaffles** [comment]
Although it _would_ be nice to have additional meta information like that for administration purposes, the data inside the list files is requested by the game itself. Anything out of spec tends to make the game either crash or throw an error.

**Comment by RenegadeRaven** [comment]
Okay. I could make a new list with the size attributes, but is it possible to have the meta info in a different file (ex: info.txt file)?

**Comment by barronwaffles** [comment]
Definitely, but the best place for it (currently) would be somewhere on the wiki - feel free to create a page or add a link on the current [download content](https://github.com/barronwaffles/dwc_network_server_emulator/wiki/Nintendo-DS-Download-Content) listing.

**Comment by RenegadeRaven** [comment]
I think I did it right. here's the pull request #508

**Comment by RenegadeRaven** [comment]
I also added the meta info to the wiki. Hopefully the way i put them there is ok with you.

**Comment by barronwaffles** [comment]
Looks good to me - feel free to close this issue and I'll get back to you with any issues regarding the pull request in the appropriate conversation area.

Thanks again!
