### ISSUE TITLE
Does anyone want to play Tatsunoko vs Capcom??? ONLINE STILL ALIVES ONLY FREE MODE

### ISSUE THREAD

**Issue by jonydark** [polaris-/dwc_network_server_emulator#51]
HELLO EVERYONE,

http://tatvscapwii.dontrush.me/gslist

https://github.com/polaris-/dwc_network_server_emulator/wiki

Have you still  wanna play Tatsunoko vs Capcom ONLINE??? Contact me: jonydark@hotmail.com
Regards URDEAD (jonydark)

**Comment by jonydark** [comment]
the new server is called Polaris

**Comment by polaris-** [comment]
This isn't the place to advertise for players.

**Comment by jonydark** [comment]
ok, where can I post that kind of things??? Thxs!!!

**Comment by mm201** [comment]
Your favourite gaming forum or to your friends.
