### ISSUE TITLE
Support large rooms in Mario Kart Wii

### ISSUE THREAD

**Issue by mm201** [polaris-/dwc_network_server_emulator#52]
Players are reporting that AltWFC is unable to handle MKW rooms with more than 4 players. 

If I had to guess, it's that the game must use a hub and spoke model similar to Mario Kart 7, which is unimplemented. In MK7, a few players are declared servers and are responsible for a subset of players and sharing their telemetry with the other player-servers.

The closure of NWFC is hardly an issue in this regard since Wiimmfi supports 12-player MKW rooms and can be captured in just the same way.

**Comment by polaris-** [comment]
Can anyone get a packet capture of this happening? The person who reported it before and again today doesn't know how to packet capture so it's kinda impossible for me to debug this at the moment.

**Comment by polaris-** [comment]
I've looked over an instance of it happening in the server logs but there are no errors anywhere, so I'm assuming it's more complicated than that. 

In fact, looking through the server logs after that some more, I see a lobby that claims to have had 6 players in it shortly after the crash even though the claim is that it crashes after 4 players. The disconnect is coming from the game side somewhere, so our server isn't forcing anyone out.

Does anyone have any idea? The only places I can think of where it could go wrong is when sending server information to a client. Maybe there's a condition that's missing somewhere? As far as I can tell, Mario Kart Wii uses a single host for the game, so I don't think it's the hub and spoke model thing mm201 mentioned. 

Actually, on second glance, I _do_ see this, but it's never caused problems before to my knowledge:
[2014-07-28 23:52:14 | GameSpyServerBrowserServer] [190.xx.xxx.xxx:57545] Received unknown command (cc) from 190.xx.xxx.xxx:57545...

**Comment by polaris-** [comment]
I made a pretty big change in the way the server browser server works. It had the potential (and most likely did) drop packets during game searches and during the process up to natneg. That means it should hopefully be a little faster now and maybe it will fix this bug.

Can anyone test if 4+ player matches in Mario Kart Wii are still broken?

**Comment by polaris-** [comment]
According to the person who reported this on IRC (Fishguy6564), 4+ player matches aren't a problem anymore after the most recent changes. So I'm closing this for now unless it pops back up in the future.
