### ISSUE TITLE
I'm getting error code 10061 "No connection could be made because the target machine actively refused it"

### ISSUE THREAD

**Issue by xNul** [polaris-/dwc_network_server_emulator#58]
When I run gamespy_natneg_server.py I get this error message:
![untitled](https://cloud.githubusercontent.com/assets/894305/3894958/dcff9b4a-2249-11e4-9c80-510cc7b41286.png)

Thanks, please help!

**Comment by polaris-** [comment]
You're not running the backend server which is required for natneg.

**Comment by xNul** [comment]
Thank you!
