### ISSUE TITLE
im having problems connecting

### ISSUE THREAD

**Issue by ghost** [polaris-/dwc_network_server_emulator#61]
I set my pokemon platinum to the servers dns and I set my wii to the servers dns nethier one wants to connect when I go to connection test in platinum I get error 52100 when I got to connection test in my wii I get error code 52130 there shouldn't be anything wrong with my wifi since my 3ds games and computer can connect but my ds games and wii wont connect to the server another strange thing is when I test it without the srervers dns it says test successful so is the server down or is there a problem with something else my games used to connect what can I do to fix these issues

**Comment by mm201** [comment]
The server is down. Please be patient.

**Comment by ghost** [comment]
oh ok do u have an idea of when itll be back or will it just randomly come back
