### ISSUE TITLE
Servers down?

### ISSUE THREAD

**Issue by Gustavo17pacheco** [polaris-/dwc_network_server_emulator#64]
Just downloaded this, patched the rom, put on my flashcart, followed the instructions, it connects to my WEP wi-fi network but doens't connect to the server... Help!

**Comment by RicoSantos** [comment]
Probably. Everyone is getting errors.

**Comment by Gustavo17pacheco** [comment]
Weird

**Comment by Gustavo17pacheco** [comment]
Guess we gotta wait

**Comment by RicoSantos** [comment]
Yeah, there's nothing we can do about it. :/

**Comment by Gustavo17pacheco** [comment]
Unfortunately

**Comment by mm201** [comment]
Our latest database backup is about a month old. If it was current, we'd be running on a backup server by now. Live and learn I guess.

**Comment by Gustavo17pacheco** [comment]
:/

**Comment by HaendelHernan** [comment]
Is there a prediction of when the servers will be back?

**Comment by Gustavo17pacheco** [comment]
Not that i know

**Comment by ghost** [comment]
So whar happened?

**Comment by ghost** [comment]
What*

**Comment by Gustavo17pacheco** [comment]
We will have to wait for Polaris to do something about it

**Comment by ghost** [comment]
hopefully Polaris does something to get the server up and running again soon

**Comment by polaris-** [comment]
Closing this since it's from the last time the server went down. But just a heads up, we moved servers. The new IP is 104.131.93.87.
