### ISSUE TITLE
Heartbeat can change data without setting statechanged

### ISSUE THREAD

**Issue by SMTDDR** [polaris-/dwc_network_server_emulator#65]
FYI, See below image.

This has caused issues for TvC since one of the parameters of the search when looking for other people is _"numplayers < 1"_.  I've changed my instance to:

```
if 'dwc_hoststate' in k and k['dwc_hoststate'] != "0":                                                                        
  self.log(logging.DEBUG, address, "Setting statechanged because dwc_hoststate != 0")
  k['statechanged'] = "1"

if "statechanged" in k:
 if k['statechanged'] == "2": # Close server
```

Which does cause redundant updates to the server list, but the data seems to be in sync better.  If other games do this and altwfc cannot rely on statechanged to always be set, then doing an update for every heartbeat might result in some games working better. FWIW, I think this is a bug in the game code.

![statechangemissing](https://cloud.githubusercontent.com/assets/3526592/4145206/b04fbea2-33f3-11e4-85f6-c899eafc6592.png)

**Comment by polaris-** [comment]
Fixed in commit #312 (8ddc427d69d384477e85d2510d201655c3d0d0c4).
