### ISSUE TITLE
nullbyte at the end of setpd commands.

### ISSUE THREAD

**Issue by SMTDDR** [polaris-/dwc_network_server_emulator#68]
I've been trying to figure out why the game stats of Tatsunoko vs Capcom weren't being saved. As it turns out, when TvC does a setpd it puts a null at the end of the data string.

Example from official-server days.

\setpd\pid\249190728\ptype\3\dindex\0\kv\1\lid\0\length\594\data\friends\SqAZevJE0phrpFckQOc7JzlMHwQZE9DUp76IYZKGnmbimMOEVYUQx2JbJQpzgEKZoGIUt4siQtfHyeiU0XyLSi7NuIvfaelbWJZ0Gq2LKHCpNFNIIldqR6P0CVTFthVk73lHt8s3mN3fW0QzZY5X1ErhI8pj6usEviAINfzYN5uxyAunwZUBcLydUKuZqaIjJS+0OiHFcnteMFs7K+WXd1JPFTwuGPfIkX7lTG32WZpRcLl02yk+D5cNAsbUYWhNYULWF4x+Q8jp2iUMYHLqUb0h4uQdyWnoUjpa8JzTGR2hTW5XF_2HO0+Bd+enDIGDbEbcb6aUMVOUlIpPondOhE2eQk2EsyZi+WD4FAlPYMy5rPxU\record\SzWeuECC_hkLblF_55LN15PJimsVfauJ2UVp1zq38dWFsIwUlJYk3uDylP_ev+Rc4q_aoiqsQxDa8uR3drC4MESH61zHoanWuOT7_jEHgFv2fkS0CnomKcZCJeu5cr2iSsXoUBSSqkimFr8ErQd2+MuxA5GSwF8kJ+AexiorCpB+LQv0ccLNQe+0lucyg4UmwnCbnTlNoXGqbJkN\final\

You don't see it here, but there's a null right before "\final\". altwfc was reading that null as part of the value of "record"_(or msg, or friends, or whatever the last field in setpd happens to be)_. That null shouldn't actually be stored in the db. When the game asks for this data back and the null is in there, the decryption fails and the game resets all stats to zero.

On my altwfc fork, I've altered this line: https://github.com/polaris-/dwc_network_server_emulator/blob/master/gamespy/gs_query.py#L53

To instead be <code>messages[key] = value.replace('\x00','') </code>, I'd be surprised if any game has a null byte as part of a valid value of a field. If other games have this issue, applying this fix might help them work better.

**Comment by AdmiralCurtiss** [comment]
Probably better to .rstrip('\x00') instead of doing a full search-replace.

**Comment by polaris-** [comment]
Updated code. Thanks for the report.

**Comment by SMTDDR** [comment]
New information has recently come to light. The null belongs there, it's fine.

**Comment by polaris-** [comment]
Can you be more specific?

**Comment by SMTDDR** [comment]
@polaris-  Actually.... I can't say in github O_o; ...in the #altwfc-dev room, _something_ happened yesterday evening. Ask Normmatt, mm201 or einstein95. But it 100% certain the nulls are not to be stripped out. I will PM you in #altwfc-dev what happened so you can check whenever.
