### ISSUE TITLE
Several fixes around setpd & getpd.

### ISSUE THREAD

**Issue by SMTDDR** [polaris-/dwc_network_server_emulator#69]
https://github.com/SMTDDR/dwc_network_server_emulator/commit/6adee00430b6232903b524d35514529fda8684f8

I can't speak about every game out there but I know how TatsunokoVSCapcom(TvC) worked. The commit above fixes stuff for TvC. Let me explain...
- **data needs an extra \ before all the data**

See official server response from back in the day:        

```
  \getpdr\1\lid\\pid\249190728\mod\1400723261\length\630\data\\record\3MRWZ0gyumuH4kUwtnVck2idXKbvVwTjWXCek+CYtlgQy8zk+wCGKch5zlZjRddLlAEyVwJ5C6qPcSqOITNsSGx2M35OA3CAktNrshI2DTBMlDE_ElZGH8JVmbUH7gfOJp9hhC+7BEC6z1TghszCo+1FM42HUekj4EKceXCFPtowQXBMfuT5AZ7r90pHfI6Ap1+fky6WBg12nzbf\msg\5mh1aqu8FxpzOvyEG89qmUQObpd2B4Mg\friends\5q9cqW3nQLJfyLfhLBIxY1xFF2VK0jatfd2X+wZbTJd0kIWGgPRqbPQTdnyLfoSk0THMUEBlrPnO25oUusgKU9pbkpeL+FGUXBS2zgrtY30dH9IoB1ePI_FQNnvA6ymxO8hfyfDKi0WAignrVLtOg9VIs3E9Y1Xxn1oy0ITL9R5mHSO9Y18Kh3+BXGX+uZQPHLmPSCQ+rn+DFGAoBfRo+FSTGxEm3OvxF5qhPJMuHAKh57_+fBSakSdAWtsMib+QC9U0vuPOtiVVoPZzSWVO_9sLhivIfUBdn8LIZGdMmCdw8HCkpG2wvb3jWn4o4dn_Z3XeX8kVNSO6xWaxWIZaGiZOOi63GQ03iAP3I98jmT8bsrX4\final\
```

See how it's "data\\". Without this extra slash, TvC doesn't know what to do and keeps resetting stats to zero. Also note that the length value is starting from the second slash after data all the way to the char that comes right before the \ in "\final\". That will give you 630. And that's only after you remove the null that TvC(imho, mistakenly) appends to the data string right before "\final\" . If you give that null back to TvC, decryption fails and all stats go to zero.
- **don't save trailing slash of data into db**

Avoid saving a trailing slash into the db as part of a value because it never is; at least for TvC and it can cause issues later when you read that value back out of the db.
- **The data string is a key-value pair like a python dictionary object**

I just noticed that altwfc was taking the data string as one column and updating the db entirely. That's now how the official servers worked. The data-string itself was a key-value pair python dictionary object. Each field in the data string could be updated without altering others. e.g., if a particular pid already has a data string in the db with a "msg" value and setpd sends a data string with only "record" in it, that data string shouldn't entirely replace what was in the db. It should "insert-or-update" the record field in the data-string and leave the msg value. So you'll see in my commit that I temporarily convert the data-string into dictionaries that I can update easily then back to string for insertion into db.
- **gamestat_profile table should have unique profileid,dindex,ptype**

I added <code>CREATE UNIQUE INDEX gamestatprofile_triple on gamestat_profile(profileid,dindex,ptype)</code> because I had many duplicates in the db and it was unclear to me which one was being given back to TvC. The official servers didn't allow duplicate data for a pid that conflicted with profileid+dindex+ptype unique key. Adding this unique index allows the <code>INSERT OR REPLACE INTO gamestat_profile</code> to do the right thing to the db.
- **Empty fields must always be returned to the game**

getpd returns all fields asked for, if db doesn't have it set them to empty string and make sure there's a \ after that empty spot. For example, if there was no msg field in the db's data string, altwfc should return "msg\\" 
-  **altwfc never detects the keys getpd is asking for.**

![image](https://cloud.githubusercontent.com/assets/3526592/4242135/e2adc59e-39fa-11e4-9f86-ee3f21093c56.png)

While this doesn't appear to harm TvC, I know the official servers obeyed so I made changes to ensure it did that.

**Comment by SMTDDR** [comment]
Closing... my fork of altwfc is taking a direction specific to TvC. Maybe it fits other games, maybe it doesn't.

**Comment by mm201** [comment]
The original server supported all the games just fine. I don't think having separate servers per game is a very good idea. All you'd basically be doing is fixing TvC-specific bugs without concern for any regressions you'd be introducing to other games.

It's also very annoying forcing players to change their DNS settings every time they want to play a different game.

**Comment by SMTDDR** [comment]
I don't do the DNS thing, I have the gamefaqs group using my Riivolution patch. <code>https://gist.github.com/SMTDDR/d9703736f0dcc7a54da3#file-smtddrudonserver-xml</code> . I also have another patch for the polaris instance, so nobody has to change DNS for this particular game. As for the whole profileID save data issues, <code>http://wiibrew.org/wiki/Savegame_Extractor</code> to switch between servers . But, my fork and all my newly added code is still very public for anyone to take and I can do a PR to get my changes merged in if you're all willing to merge & restart altwfc. I only run it myself because I can make changes faster. e.g., this issue was open for almost a month without anything happening. It's just that I'm focused on TvC and apparently have more free time to spend on this game. I even plan to moderate and ban people if the need arises. I thought this would all be too much of a burden for the official altwfc-devs for just one game.

**Comment by polaris-** [comment]
> I only run it myself because I can make changes faster. e.g., this issue was open for almost a month without anything happening

You're already making changes to your repository. You should be submitting pull requests, not waiting for us to independently go through your list and fix everything again. I've been really busy with school and other stuff lately so I don't have the time to go through and fix everything like I used to. I'm pretty sure I told you on IRC before that you should submit pull requests instead of just waiting for it to happen.

**Comment by SMTDDR** [comment]
ok, PR created
