### ISSUE TITLE
server lag

### ISSUE THREAD

**Issue by ghost** [polaris-/dwc_network_server_emulator#70]
my wii can connect but it takes a long time then my ds games wont connect because it takes too long for them to is there lag in the server or something

**Comment by HaendelHernan** [comment]
The servers are down again. I can't connect. My shiny Boldore is stuck on the GTS :(

**Comment by ghost** [comment]
they are then how can my wii and brawl connect

**Comment by HaendelHernan** [comment]
They're back, yay
