### ISSUE TITLE
Are servers up?

### ISSUE THREAD

**Issue by Maganet** [polaris-/dwc_network_server_emulator#71]
Are the servers up yet? If so I cant connect to them. I have done everything that is needed, and i keep getting error code 20100. Also do I have to have the Bypass HTTPS code activated every time I want to go online? Thnak you

**Comment by mm201** [comment]
Yes, the servers are up. Yes, you need to use an SSL disabling patch/code to connect.
Have you configured the special DNS?

**Comment by gab3587** [comment]
Yes, the servers are up.
20100: Connection to the Access Point succeeded, but connection to the Wi-Fi Connection servers couldn't be established. Either you forgot to set the DNS and are trying to connect to the now-defunct official servers, or the custom server is currently down for maintenance. May also be a result of not properly patching your game to remove the SSL checks.

https://github.com/polaris-/dwc_network_server_emulator/wiki/Troubleshooting

**Comment by Maganet** [comment]
Also the latest version of WfcReplay isnt working for me. This is the massage that pops up when I try to create a code for my game: A fatal error occurred. However, mscorees.dll could not be loaded to display the appropriate error massage.

Please reinstall the .NET Framework.

I need help fixing this.

**Comment by polaris-** [comment]
Server is up. If anyone else has the same question in the future, check the page running at port 9001 on the server (currently http://104.131.93.87:9001/) to see if it responds. Closing ticket.

For issues with WfcReplay, report them to the WfcReplay issue tracker: https://github.com/Prof9/wfcreplay
