### ISSUE TITLE
Mystery Gift Doesn't work on Pokemon BW1/2

### ISSUE THREAD

**Issue by ghost** [polaris-/dwc_network_server_emulator#79]
Hello,

I discovered a bug : Mystery gift doesn't work with french version of Pokemon BW1/2, and random fight doesn't work online (there are a matchmaking bug).

**Comment by mid-kid** [comment]
Matchmaking is nonexistent at the moment, AFAIK.

**Comment by AdmiralCurtiss** [comment]
French Mystery Gifts have been added.

**Comment by polaris-** [comment]
Server has been updated. French Mystery Gifts should be working now.

**Comment by ghost** [comment]
Thanks polaris, do you have Skype ? I want to speak with you ^^

**Comment by polaris-** [comment]
I do but it's private. If it's something private then you can message me on here or on IRC.
