### ISSUE TITLE
Ocarina code

### ISSUE THREAD

**Issue by THEDARKK** [polaris-/dwc_network_server_emulator#82]
Hello, is that the new Ocarina code is out? 

kind regards

**Comment by polaris-** [comment]
What would a new Ocarina code be needed for? As far as I know, the Ocarina code doesn't include anything server-specific, so the old one should still work with the new server. I'm not knowledgeable about Wii things so I'll wait for someone to come in with a better response, or to tell me if it's ok to close this ticket or not.

**Comment by ToadKing** [comment]
The ocarina code does the exact same thing as the DS game patcher and brainslug launcher. A new one is not needed.
